### PR TITLE
Handle memory consumption in the ballpark of MiBs too

### PR DESCRIPTION
**Pull request by keynslug**
Use proper IEC unit prefixes also in output.

### CODE REVIEW

**Comment by seriyps** [comment]
Merged, thanks!

**Comment by keynslug** [comment]
May I propose making 0.2.1 release maybe? It would be great to have more recent package available on hex.

**Comment by seriyps** [comment]
Sure, good idea.

**Comment by seriyps** [comment]
done (git tag and hex.pm)

**Comment by keynslug** [comment]
Thanks!

**Pull request merged**
